project_id = "tjdhbdtkotmnjatnliij"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-class-confirmations]
    verify_jwt = false
  [functions.whatsapp-webhook]
    verify_jwt = false
